version: 2
jobs:
  build:
    working_directory: ~/zen
    
    docker:
      - image: circleci/ruby:2.4.1-node

      - image: circleci/postgres:9.6.3-alpine

      - image: redis@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673
    steps:
      - checkout

      - run:
          name: Install build-essential, libpq-dev
          command: 'sudo apt-get install -y build-essential libpq-dev'

      - type: cache-restore
        key: zen-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          key: zen-{{ checksum "package.json" }}-{{ checksum "client/package.json" }}

      - run:
          name: update-yarn
          command: 'sudo npm install -g yarn@latest'

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      - type: cache-save
        key: zen-{{ checksum "Gemfile.lock" }}
        paths:
            - vendor/bundle

      - type: cache-save
        key: zen-{{ checksum "package.json" }}-{{ checksum "client/package.json" }}
        paths:
            - .node_modules
            - client/.node_modules

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
